
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths: ["test","example","node_modules","jspm_packages"]
engines: 
  eslint:
    enabled: true
  